### ISSUE TITLE
Update Releases with latest changes?

### ISSUE THREAD

**Issue by FishamanP** [windyfairy/2dxrender#1]
Quickly attempted to build myself but I don't feel like grabbing all the dependencies. It seems like commits have slowed down, so a new release might be in order.

**Comment by windyfairy** [comment]
The build that's up right now should be fine for most people's use case I think. The only changes after that build, from Feb 3rd, only affect the JSON parsing code which is independent of the .1 parsing code. 

If you're only parsing .1 files straight from AC then you're fine. 

If you're using JSON files dumped from the PS2 games then I can upload a new build but I wouldn't recommend it quite yet since the PS2 chart parsing code in my other repo is still a bit buggy in areas, resulting in some bad timing in songs from the earlier games.

**Comment by windyfairy** [comment]
@FishamanP I have CircleCI running builds every time I push code to master now. It will automatically build and upload new releases to the release tab. So the latest revision of the code + any future changes should automatically be made available from now on.
